FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

COPY src/. .

WORKDIR /src/TaskTracker/IdentityService/TaskTracker.IdentityService.Api

RUN dotnet restore TaskTracker.IdentityService.Api.csproj

RUN dotnet publish TaskTracker.IdentityService.Api.csproj -c Release -o /app

FROM mcr.microsoft.com/dotnet/aspnet:8.0
WORKDIR /app

COPY --from=build /app .

EXPOSE 8080

ENTRYPOINT ["dotnet", "TaskTracker.IdentityService.Api.dll"]
